[package]
name = "remember-ffi"
version.workspace = true
edition.workspace = true

[lib]
name = "remember_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["cli"]

[dependencies]
thiserror = "2.0.20"
remember-core = { version = "0.1.0", path = "../core" }
remember-sync = { version = "0.1.0", path = "../sync" }
uniffi = { version = "0.32.0" }

[features]
cli = ["uniffi/cli"]
