name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "Casks/**"
  pull_request:

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Install Rust
        run: |
          rustup component add clippy rustfmt llvm-tools-preview

      - name: Install cargo-nextest and cargo-llvm-cov
        run: |
          cargo install --locked cargo-nextest cargo-llvm-cov

      - name: cargo xtask ci
        run: cargo xtask ci
